# -*- coding: utf-8 -*-
"""SENTIMENT ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bLf0Vf2qcr9_M36lCUH4SpT-9oVP1uR
"""

#installing kaggle liraries
! pip install kaggle

#configuring the path of kaggle.jason file
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

"""# Importing Twitter Sentiment **Dataset**"""

# API to fetch the dataset from kaggle
!kaggle datasets download -d kazanova/sentiment140

#Extracting the compressed Dataset
from zipfile import ZipFile
dataset = '/content/sentiment140.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

"""# Importing the Dependencies"""

import pandas as pd
import numpy as np
import re
# Download required resources for NLTK
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
# Make sure scikit-learn is updated
!pip install --upgrade scikit-learn
from sklearn.feature_extraction.text import TfidfVectorizer # Fixed typo here: It's TfidfVectorizer, not TfidVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#printing the stopwords in english
print(stopwords.words('english'))

"""**Data** **Processing**"""

# loading the data from csv file to dataframe
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',encoding='ISO-8859-1')

# checking the number of rows and columns
twitter_data.shape

#printing the first 5 rows of dataframe
twitter_data.head()

#naming the coluns and reading the dataset again
column_names = ['target', 'ids', 'date', 'flag', 'user', 'text']
twitter_data = pd.read_csv('/content/training.1600000.processed.noemoticon.csv',names= column_names, encoding='ISO-8859-1')

# checking the number of rows and columns
twitter_data.shape

#printing the first 5 rows of dataframe
twitter_data.head()

# counting the number of missing values in dataset
twitter_data.isnull().sum()

# checking the distribution of target column
twitter_data['target'].value_counts()

"""# CONVERT THE TARGET "4" TO "1"
"""

twitter_data.replace({'target':{4:1}}, inplace=True)

# checking the distribution of target column
twitter_data['target'].value_counts()

"""# 0--> Negative Tweet
# 1--> Positive Tweet

**Stemming**

stemming is a process of reducing a word to its Root word.

eg. actoress, actor, acting = act
"""

port_stem = PorterStemmer()

def stemming(content):
  stemmed_content = re.sub('[^a-zA-Z]',' ',content)
  stemmed_content = stemmed_content.lower()
  stemmed_content = stemmed_content.split()
  stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
  stemmed_content = ' '.join(stemmed_content)
  return stemmed_content

twitter_data['stemmed_content'] = twitter_data['text'].apply(stemming) # huge time to execte because of a big data

twitter_data.head()

print(twitter_data['stemmed_content'])

#seperating the data and labels
X = twitter_data['stemmed_content'].values
Y = twitter_data['target'].values

print(X)

print(Y)

"""Splitting the data to training data and test data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(X.shape,X_train.shape,X_test.shape)

print(X_train)

print(X_test)

#converting the textual data to numerical data
vectorizer = TfidfVectorizer()
vectorizer.fit(X_train)

X_train = vectorizer.transform(X_train)
X_test = vectorizer.transform(X_test)

print(X_train)

print(X_test)

"""# **Training the Machine Learning**

Logistic regression
"""

model = LogisticRegression(max_iter=1000)

model.fit(X_train,Y_train)

"""# **Model Evaluation**
Accuracy score
"""

# accuracy score on the training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

print('Accuracy score on the training data: ',training_data_accuracy)

# accuracy score on the test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

print('Accuracy score on the training data: ',training_data_accuracy)

"""Model accuracy = 79.87%


Saving the trained model
"""

import pickle

filename='trained_model.sav'
pickle.dump(model,open(filename,'wb'))

"""Using the saved model for future Predictions."""

#loading the trained model.
loaded_model= pickle.load(open('/content/trained_model.sav','rb'))

X_new = X_test[200]
print(Y_test[200])
prediction= loaded_model.predict(X_new)
print(prediction)
if (prediction[0]==0):
  print('negative tweet')
else:
  print('positive tweet')

X_new=X_test[3]
print(Y_test[3])
prediction= loaded_model.predict(X_new)
print(prediction)
if (prediction[0]==0):
  print('negative tweet')
else:
  print('positive tweet')

import pandas as pd

# Try ISO-8859-1 encoding (works for Twitter data)
df = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding='ISO-8859-1')

print(df.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding='ISO-8859-1', header=None)

# Rename columns properly
df.columns = ['target', 'ids', 'date', 'flag', 'user', 'text']

# Map the target: 0 = Negative, 4 = Positive
df['sentiment'] = df['target'].map({0: 'Negative', 4: 'Positive'})

# Show only 5 elements
print(df[['text', 'sentiment']].head())

# Plot the sentiment distribution
plt.figure(figsize=(8,6))
sns.countplot(data=df, x='sentiment', palette='coolwarm')
plt.title('Sentiment Distribution')
plt.xlabel('Sentiment')
plt.ylabel('Number of Tweets')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load and prepare your dataset
df = pd.read_csv('/content/training.1600000.processed.noemoticon.csv', encoding='ISO-8859-1', header=None)
df.columns = ['target', 'ids', 'date', 'flag', 'user', 'text']
df['sentiment'] = df['target'].map({0: 'Negative', 4: 'Positive'})

# Count the number of Positive and Negative tweets
sentiment_counts = df['sentiment'].value_counts()

# Print the result
print("Sentiment Counts:")
print(sentiment_counts)

# Bar graph showing difference
plt.figure(figsize=(8,6))
plt.bar(sentiment_counts.index, sentiment_counts.values, color=['red', 'green'])
plt.title('Difference Between Positive and Negative Tweets')
plt.xlabel('Sentiment')
plt.ylabel('Number of Tweets')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

sentiment_counts = df['sentiment'].value_counts()

plt.figure(figsize=(8,8))

plt.pie(
    sentiment_counts.values,
    labels=sentiment_counts.index,
    autopct='%1.1f%%',
    startangle=140
)

plt.title('Sentiment Proportions')
plt.axis('equal')

plt.savefig("sentiment_pie_chart.png")  # for GitHub
plt.show()

import numpy as np
import pandas as pd

# Add synthetic demographic columns
np.random.seed(42)
n = len(df)

df['Age'] = np.random.randint(18, 70, size=n)
df['Income'] = np.random.normal(loc=60000, scale=15000, size=n).clip(20000, 150000)
df['Gender'] = np.random.choice(['M', 'F'], size=n)
df['Membership'] = np.random.choice(['Bronze', 'Silver', 'Gold'], size=n, p=[0.2, 0.5, 0.3])
df['City'] = np.random.choice(['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Pune'], size=n)

# Create Age_Group
df['Age_Group'] = pd.cut(df['Age'], bins=[0, 18, 35, 60, np.inf], labels=['Child', 'Young Adult', 'Adult', 'Senior'])

# Standardized Income (Z-score)
df['Income_Standardized'] = (df['Income'] - df['Income'].mean()) / df['Income'].std()

# Income Bin (Quantile-based)
df['Income_Bin'] = pd.qcut(df['Income'], q=3, labels=['Low', 'Medium', 'High'])

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore

# Setup plot style
sns.set(style="whitegrid")

# 1. Age Distribution (Histogram)
plt.figure(figsize=(8,6))
sns.histplot(df['Age'], bins=20, kde=True, color='cornflowerblue')
plt.title('Age Distribution of Customers')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

# 2. Income Distribution (Boxplot)
plt.figure(figsize=(8,6))
sns.boxplot(x='Income', data=df, color='lightgreen')
plt.title('Income Distribution with Outliers')
plt.xlabel('Income')
plt.show()

# 3. Membership Level Count (Bar Chart)
plt.figure(figsize=(8,6))
sns.countplot(x='Membership', data=df, palette='Set2')
plt.title('Membership Level Distribution')
plt.xlabel('Membership')
plt.ylabel('Number of Customers')
plt.show()

# 4. Gender Distribution (Pie Chart)
gender_counts = df['Gender'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=140, colors=['lightblue', 'lightpink'])
plt.title('Gender Distribution')
plt.axis('equal')
plt.show()

# 5. Age Group vs Membership (Stacked Bar Chart)
cross_tab = pd.crosstab(df['Age_Group'], df['Membership'])
cross_tab.plot(kind='bar', stacked=True, figsize=(8,6), colormap='Accent')
plt.title('Age Group vs Membership Level')
plt.xlabel('Age Group')
plt.ylabel('Number of Customers')
plt.legend(title='Membership')
plt.xticks(rotation=0)
plt.show()

# 6. Income by Age Group (Violin Plot)
plt.figure(figsize=(8,6))
sns.violinplot(x='Age_Group', y='Income', data=df, palette='Set3')
plt.title('Income Distribution by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Income')
plt.show()

# 7. Standardized Income Distribution (Histogram)
plt.figure(figsize=(8,6))
sns.histplot(df['Income_Standardized'], bins=30, kde=True, color='mediumpurple')
plt.title('Standardized Income Distribution')
plt.xlabel('Standardized Income')
plt.ylabel('Frequency')
plt.show()

# 8. City-Wise Customer Count (Bar Plot)
top_cities = df['City'].value_counts().nlargest(10)
plt.figure(figsize=(10,6))
sns.barplot(x=top_cities.index, y=top_cities.values, palette='Blues')
plt.title('Top 10 Cities by Customer Count')
plt.xlabel('City')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45)
plt.show()

# 9. Income Binning (Count Plot)
plt.figure(figsize=(8,6))
sns.countplot(x='Income_Bin', data=df, palette='coolwarm')
plt.title('Customer Count by Income Category')
plt.xlabel('Income Bin')
plt.ylabel('Number of Customers')
plt.show()